project_id = "fttdfvnhghbgtawkslau"

[functions.trigger-n8n-workflow]
verify_jwt = true

[functions.save-workflow-message]
verify_jwt = false

[functions.upsert-company]
verify_jwt = false

[functions.advance-pipeline]
verify_jwt = false

[functions.check-openai-limits]
verify_jwt = false

[functions.remove-duplicate-companies]
verify_jwt = false

[functions.remove-duplicate-emails]
verify_jwt = false
